package com.twj.math.constants;

import java.util.List;

public class QuestionConstants {
    public static List<String> lNames =
            List.of("Olivia",
                    "Emma",
                    "Charlotte",
                    "Amelia",
                    "Ava",
                    "Sophia",
                    "Isabella",
                    "Mia",
                    "Evelyn",
                    "Harper",
                    "Luna",
                    "Camila",
                    "Gianna",
                    "Elizabeth",
                    "Eleanor",
                    "Ella",
                    "Abigail",
                    "Sofia",
                    "Avery",
                    "Scarlett",
                    "Emily",
                    "Aria",
                    "Penelope",
                    "Chloe",
                    "Layla",
                    "Mila",
                    "Nora",
                    "Hazel",
                    "Madison",
                    "Ellie",
                    "Lily",
                    "Nova",
                    "Isla",
                    "Grace",
                    "Violet",
                    "Aurora",
                    "Riley",
                    "Zoey",
                    "Willow",
                    "Emilia",
                    "Stella",
                    "Zoe",
                    "Victoria",
                    "Hannah",
                    "Addison",
                    "Leah",
                    "Lucy",
                    "Eliana",
                    "Ivy",
                    "Everly",
                    "Lillian",
                    "Paisley",
                    "Elena",
                    "Naomi",
                    "Maya",
                    "Natalie",
                    "Kinsley",
                    "Delilah",
                    "Claire",
                    "Audrey",
                    "Aaliyah",
                    "Ruby",
                    "Brooklyn",
                    "Alice",
                    "Aubrey",
                    "Autumn",
                    "Leilani",
                    "Savannah",
                    "Valentina",
                    "Kennedy",
                    "Madelyn",
                    "Josephine",
                    "Bella",
                    "Skylar",
                    "Genesis",
                    "Sophie",
                    "Hailey",
                    "Sadie",
                    "Natalia",
                    "Quinn",
                    "Caroline",
                    "Allison",
                    "Gabriella",
                    "Anna",
                    "Serenity",
                    "Nevaeh",
                    "Cora",
                    "Ariana",
                    "Emery",
                    "Lydia",
                    "Jade",
                    "Sarah",
                    "Eva",
                    "Adeline",
                    "Madeline",
                    "Piper",
                    "Rylee",
                    "Athena",
                    "Peyton",
                    "Everleigh");
    public static List<String> lItems =
            List.of("pencils",
                    "cookies",
                    "sweets",
                    "highlighters",
                    "books",
                    "beads",
                    "clothes",
                    "bottles of slime",
                    "dolls",
                    "balls",
                    "teddy bears",
                    "rubber ducks",
                    "toy cars",
                    "toy trains",
                    "balloons",
                    "sand buckets",
                    "LOL surprise eggs",
                    "paw patrol figurines",
                    "star wars figurines",
                    "drums",
                    "barbie dolls",
                    "lego sets",
                    "crayons");
    public static List<String> lItem =
            List.of("mechnical pencil",
                    "cookie",
                    "packet of sweet",
                    "box of highlighter",
                    "book",
                    "bag of bead",
                    "skirt",
                    "bottle of slime",
                    "doll",
                    "ball",
                    "teddy bear",
                    "rubber duck",
                    "toy car",
                    "toy train",
                    "balloon",
                    "sand bucket",
                    "LOL surprise",
                    "paw patrol figurine",
                    "star wars figurine",
                    "drum set",
                    "barbie doll",
                    "box of lego",
                    "box of crayon");
}
